services:
  - type: web
    name: recro-ts-generator
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    healthCheckPath: /
    ignoredPaths:
      - README.md
      - .github/**
